package com.ensi.Model;





import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
* Role generated by hbm2java
*/
@Entity
@Table(name = "role") 
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRole;
	private String name;
	private String type;
	private List<User> users;

	public Role() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinTable(name = "user_has_role", 
	joinColumns = { @JoinColumn(name = "Role_idRole", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "User_idUser", nullable = false, updatable = false) })
	public List<User> getUsers() {
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}
	public String getType() {
		return type;
	}



	public Role(Integer idRole, String name, String type, List<User> users) {
		super();
		this.idRole = idRole;
		this.name = name;
		this.type = type;
		this.users = users;
	}



	public void setType(String type) {
		this.type = type;
	}

}
